table Wettbewerbspreise
	lineageTag: 051fe88d-09dd-43a1-93fd-1db6a0a17d47

	column produkt_id
		dataType: string
		lineageTag: d9c41c1b-5276-4e6f-bf1f-dc6168fac937
		summarizeBy: none
		sourceColumn: produkt_id

		annotation SummarizationSetBy = Automatic

	column datum
		dataType: dateTime
		formatString: dd.MM.yyyy
		lineageTag: 10e4f3d4-953a-4e25-ab51-637d2fb02781
		summarizeBy: none
		sourceColumn: datum

		variation Variation
			isDefault
			relationship: fbd28192-8142-48db-a96a-decc46b6bbb0
			defaultHierarchy: LocalDateTable_8a0d6ba5-925a-44ce-b508-6dfeb93a406a.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column wettbewerbspreis
		dataType: double
		formatString: #,0.00" €"
		lineageTag: 6e4e4edd-d8d5-43fa-bddc-cccd6e0081b4
		summarizeBy: sum
		sourceColumn: wettbewerbspreis

		annotation SummarizationSetBy = Automatic

	partition Wettbewerbspreise = m
		mode: import
		source =
				let
				    DataPath = try #"DataPath" otherwise "../data",
				    Quelle = Csv.Document(
				        File.Contents(DataPath & "/wettbewerbspreise.csv"),
				        [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    HeadersHochgestuft = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    TypGeändert = Table.TransformColumnTypes(HeadersHochgestuft, {
				        {"produkt_id",      type text},
				        {"datum",           type date},
				        {"wettbewerbspreis", type number}
				    })
				in
				    TypGeändert

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

